FFC-171848: Defra Id Register your interest
DEFRA/ffc-ahwr-farmer-apply pull request #118
Opened 2023-04-05 14:27 UTC by json-hamilton

…creen

2023-04-05 15:31 UTC, liamwilson-kainos requested changes

2023-04-05 15:31 UTC, liamwilson-kainos commented on app/routes/register-your-interest/register-your-interest.js
> +          return h.view('defra-id/register-your-interest/register-your-interest', { ruralPaymentsAgency })
could probably remove the duplicate registration of interest and have this as an index page?

2023-04-05 15:31 UTC, liamwilson-kainos commented on app/views/defra-id/register-your-interest/register-your-interest.njk
> +    <p>If you do not have an account, <a href="https://www.ruralpayments.service.gov.uk/">register with the Rural Payments service.</a></p>
rural payment service url should also be coming from the config and we can pass a value for it into this page

2023-04-11 14:01 UTC, liamwilson-kainos requested changes

2023-04-11 14:01 UTC, liamwilson-kainos commented on app/routes/register-your-interest/index.js
> +          if (defraIdConfig.enabled === true) {
not sure if we need this check seeing that we will only ever POST to `register-your-interest` once DEFRA ID is enabled. Also we need to make sure when we submit the form we are sending the message to the queue - .e.g.

`await sendRegisterYourInterestMessage(sbi, crn, emailAddress)`

2023-04-11 14:01 UTC, liamwilson-kainos commented on app/routes/register-your-interest/index.js
> +        if (defraIdConfig.enabled === true) {
not sure we even need the enabled check as when turned off i don't think we ever POST to `register-your-interest`

2023-04-13 07:47 UTC, liamwilson-kainos submitted a review, later dismissed

2023-04-13 07:47 UTC, liamwilson-kainos commented on app/routes/register-your-interest/index.js
> +      await sendEmail(registerYourInterest, request.payload.emailAddress)
We can use this new template which is a registration of interest confirmation V2 (new for defra id)-> 

https://www.notifications.service.gov.uk/services/4e30070f-25e2-40df-8add-e4375408638f/templates/8c6d9dc1-127d-4355-a16c-cc5fd522f64f

ID is 8c6d9dc1-127d-4355-a16c-cc5fd522f64f

2023-04-13 07:47 UTC, liamwilson-kainos commented on app/views/defra-id/register-your-interest/registration-complete.njk
> +        titleText: "Registration complete - DRAFT PAGE"
we could replace the placeholder content with https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/170010/ and form the prototype  https://fcp-ahwr-prototype.herokuapp.com/v10/registration/confirmation

2023-04-13 13:13 UTC, chrissmKainos commented on app/views/defra-id/register-your-interest/index.njk
> +    <p class="govuk-heading-body">The Rural Payments Agency will contact you with a link to start your application as soon as possible.</p>
Prototype show '_Rural Payments Agency (RPA)_'

https://fcp-ahwr-prototype.herokuapp.com/v10/registration/register

2023-04-13 13:15 UTC, chrissmKainos commented on app/views/defra-id/register-your-interest/index.njk
> +    <p class="govuk-body">If you cannot apply online or have a question about your application contact the Rural Payments Agency by email or phone.</p>
Different text in the prototype, '_If you cannot apply online or have a question..._' is '_If you have another question about your registration..._'

https://fcp-ahwr-prototype.herokuapp.com/v10/registration/register

2023-04-13 14:05 UTC, chrissmKainos submitted a review, later dismissed

2023-04-14 08:59 UTC, marcin-mogiela submitted a review, later dismissed

2023-04-18 08:16 UTC, liamwilson-kainos approved these changes

2023-04-19 12:49 UTC, liamwilson-kainos approved these changes

2023-04-19 12:51 UTC, merged